name: Build Docker Image

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: docker/build-push-action@v2
        with:
          dockerfile: ./Dockerfile
          push: false
